# Numpy - Criação de Arrays e Operações

**Disciplina**: Programação para Ciência dos Dados  
**Docentes**: Elloá B. Guedes e Tiago E. de Melo  
**Contato:** ebgcosta@uea.edu.br, tmelo@uea.edu.br  
**Github:** http://github.com/elloa/numpy

## Apresentação

Este notebook deverá ser utilizado para a prática dos conceitos relativos à biblioteca numpy.

In [9]:
import numpy as np

## Parte 1.1: Criação de ndarrays

1. Crie um ndarray a partir de uma lista de inteiros de 1 a 100
2. Obtenha o tipo do objeto e o tipo de dados nele contidos
3. Qual a dimensão deste array?
4. Obtenha o rank deste array.
4. Crie um novo array de dimensão (100,1) a partir da lista inicial
5. Crie um ndarray de rank igual a 3 e dimensões 2x2x2

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
a1 = np.array([x for x in range(1,101)])
a1

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
type(a1)

numpy.ndarray

In [14]:
a.shape

(4,)

In [15]:
a.dtype

dtype(&#39;int32&#39;)

In [17]:
b = np.array([[x] for x in range(1, 101)])
b

array([[  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27],
       [ 28],
       [ 29],
       [ 30],
       [ 31],
       [ 32],
       [ 33],
       [ 34],
       [ 35],
       [ 36],
       [ 37],
       [ 38],
       [ 39],
       [ 40],
       [ 41],
       [ 42],
       [ 43],
       [ 44],
       [ 45],
       [ 46],
       [ 47],
       [ 48],
       [ 49],
       [ 50],
       [ 51],
       [ 52],
       [ 53],
       [ 54],
       [ 55],
       [ 56],
       [ 57],
       [ 58],
       [ 59],
       [ 60],
       [ 61],
       [ 62],
       [ 63],
       [ 64],
       [ 65],
       [ 66],
       [ 67],
       [ 68],
       [ 69],
       [ 70],
       [ 71],
      

In [22]:
b.dtype

dtype(&#39;int32&#39;)

In [21]:
b.astype("int64")

array([[  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  6],
       [  7],
       [  8],
       [  9],
       [ 10],
       [ 11],
       [ 12],
       [ 13],
       [ 14],
       [ 15],
       [ 16],
       [ 17],
       [ 18],
       [ 19],
       [ 20],
       [ 21],
       [ 22],
       [ 23],
       [ 24],
       [ 25],
       [ 26],
       [ 27],
       [ 28],
       [ 29],
       [ 30],
       [ 31],
       [ 32],
       [ 33],
       [ 34],
       [ 35],
       [ 36],
       [ 37],
       [ 38],
       [ 39],
       [ 40],
       [ 41],
       [ 42],
       [ 43],
       [ 44],
       [ 45],
       [ 46],
       [ 47],
       [ 48],
       [ 49],
       [ 50],
       [ 51],
       [ 52],
       [ 53],
       [ 54],
       [ 55],
       [ 56],
       [ 57],
       [ 58],
       [ 59],
       [ 60],
       [ 61],
       [ 62],
       [ 63],
       [ 64],
       [ 65],
       [ 66],
       [ 67],
       [ 68],
       [ 69],
       [ 70],
       [ 71],
      

In [19]:
b.shape

(100, 1)

In [20]:
b.ndim

2

In [24]:
%time c = np.array([[[1,0]]])

Wall time: 0 ns


É possível criar um ndarray a partir da lista a seguir?

$$lista = [[1,2],[3,4,5],[6,7,8,9]]$$

Qual o tipo de dados contidos no array criado a partir da lista a seguir?

$$[-1, 1, 2.0, 3.15]$$

## Parte 1.2: Coerção de tipos em ndarrays


0. Cuidado!
1. **Primeira forma**: passar o dtype como parâmetro  
```python
np.array([1,2,3],dtype = "complex")
```
2. **Segunda forma**: coerção de tipos
```python
a = np.array([1,2,3])
a = a.astype("float")
```
3. Os tipos de dados disponíveis na biblioteca numpy são listados em:  
https://numpy.org/devdocs/user/basics.types.html


Quais as implicações da coerção de tipo a seguir? Execute e observe.

```python
x = np.array([1.3 + 3j,2 -4j],dtype = "complex_")
x = x.astype("int")
```

## Parte 1.3: Criação intrínseca de arrays

1. A partir de np.zeros: Crie uma matriz identidade 3x3 de números inteiros
2. A partir de um array unidimensional de np.ones: Crie um array 2x10 preenchido apenas com $\pi$
3. Qual a consequência da execução do código a seguir?
```python
np.random.random((2,2)).reshape(3,3)
```
4. Criar um array unidimensional a partir de uma variável aleatória com distribuição normal de média zero e desvio padrão igual a 1.0  
  - https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html
  - Que tal plotar um histograma destes dados?
5. Criar amostras no intervalo de [1,100] intervaladas de 0.1  
   5.1 Com uma lista  
   5.2 Com np.arange  
6. Crie um linspace no intervalo $[-2\pi,2\pi]$ com mil amostras  
   6.1 Obtenha o seno e o coseno destes valores  
   6.2 Plote o gráfico destas funções  

## Parte 2.1 - Operações elemento-a-elemento

1. Crie um array bidimensional (2,5) de uns
2. Crie um array mesmo formato que o anterior, mas gerado aleatoriamente de maneira uniforme
3. Some os dois arrays e armazene o resultado em uma variável
2. Eleve os elementos do array anterior ao quadrado e, em seguida, subtraia 1

In [28]:
%time a = np.ones((2,5))
a

Wall time: 0 ns


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [32]:
b = np.random.random((2,5))
b

array([[0.6987559 , 0.15745457, 0.2576695 , 0.31336597, 0.27518626],
       [0.81583556, 0.54479772, 0.27903866, 0.01883434, 0.23001149]])

In [33]:
%time a + b

Wall time: 0 ns


array([[1.6987559 , 1.15745457, 1.2576695 , 1.31336597, 1.27518626],
       [1.81583556, 1.54479772, 1.27903866, 1.01883434, 1.23001149]])

## Parte 2.2 - Multiplicando arrays

1. Obtenha 2 arrays aleatoriamente gerados de dimensão 2x2
2. Multiplique as matrizes com o operador * e justifique o resultado
3. Multiplique as matrizes com o produto dot
4. Verifique se as operações a seguir são possíveis. O que as impede de ser realizada?
```python
a = np.ones((1,5))
b = np.random.random((3,2))
a*b
a.dot(b)
```


## Parte 2.3 -- Funções Universais (ufunc)

1. Crie um linspace no intervalo $[-1,+1]$ com cem amostras  
2. Obtenha e plote a função tangente neste intervalo (não use np.tan!)
3. A função sigmóide é muito importante no contexto das redes neurais:

$$f(x) = \frac{1}{1 + e^{-\beta \cdot x}}$$


   3.1 Crie um linspace no intervalo $[-2,+2]$ com 200 amostras  
   3.2 Construa uma função em Python que implemente a equação anterior. Utilize um parâmetro nomeado $\beta = 1$  
   3.3 Aplique-a no linspace previamente definido e plote o resultado obtido  
   3.4 Incremente o gráfico anterior com $\beta = 0.8$ e $\beta = 1.2$, para comparar a curva gerada  
   3.5 Capriche no gráfico e inclua legendas!

## Parte 2.4 -- Funções agregadas

1. Crie um array de 1500 números *inteiros* aleatórios no intervalo $[0,100)$ com distribuição uniforme
2. Calcule a média e o desvio padrão
3. Suponha que o seu array esteja armazenado na variável a. Execute o código a seguir:

```python
unique, counts = numpy.unique(a, return_counts=True)
d = dict(zip(unique, counts))
print(d)
```
4. Obtenha o valor que mais se repete no vetor inicial